name: Sign Image
description: Sign the images with GitHub OIDC Token.
author: support@senzing.com

inputs:
  digest:
    description: Image digest
    required: true
  image-tags:
    description: Image tags
    required: true

runs:
  using: composite
  steps:
    - name: Sign the DockerHub images with GitHub OIDC Token
      env:
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
        TAGS: ${{ steps.docker_meta_dockerhub.outputs.tags }}
      run: |
        images=""
        for tag in ${{ inputs.image-tags }}; do
          images+="${tag}@${{ inputs.digest }} "
        done
        cosign sign --yes ${images}
        for tag in ${{ inputs.image-tags }}; do
          echo "[INFO] cosign verify --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
          --certificate-identity=https://github.com/${{ github.workflow_ref }} \
          ${tag}"
        done
      shell: bash
