name: Sign Image
description: Sign the images with GitHub OIDC Token.
author: support@senzing.com

inputs:
  digest:
    description: Image digest
    required: true
  image-repository:
    description: Docker repository (e.g. senzing/senzingapi-runtime)
    required: true
  image-tag:
    description: Image tag
    required: true
  image-tags:
    description: Image tags
    required: true
  registry-server:
    default: docker.io
    description: Docker registry server
    required: true

runs:
  using: composite
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3

    - name: Sign the DockerHub images with GitHub OIDC Token
      env:
        IMAGE_TAGS: ${{ inputs.image-tags }}
        IMAGE_DIGEST: ${{ inputs.digest }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        IMAGE_REPOSITORY: ${{ inputs.image-repository }}
        REGISTRY_SERVER: ${{ inputs.registry-server }}
        WORKFLOW_REF: ${{ github.workflow_ref }}
      run: |
        set -x
        images=""
        echo "[INFO] image tags: $IMAGE_TAGS"
        while IFS= read -r line || [[ -n $line ]]; do
          echo "[INFO] line: $line"
          images+="${line}@${IMAGE_DIGEST} "
          echo "[INFO] images: $images"
        done < <(printf '%s' "$IMAGE_TAGS")

        echo "[INFO] images final: $images"

        echo "[INFO] cosign sign --yes ${images}"
        cosign sign --yes ${images}

        echo "[INFO] cosign verify --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
          --certificate-identity=https://github.com/${WORKFLOW_REF} \
          ${REGISTRY_SERVER}/${IMAGE_REPOSITORY}:${IMAGE_TAG}"
        cosign verify --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
          --certificate-identity=https://github.com/${WORKFLOW_REF} \
          "${REGISTRY_SERVER}/${IMAGE_REPOSITORY}:${IMAGE_TAG}"
      shell: bash
