name: Sign Image
description: Sign the images with GitHub OIDC Token.
author: support@senzing.com

inputs:
  digest:
    description: Image digest
    required: true
  image-repository:
    description: Docker repository (e.g. senzing/senzingapi-runtime)
    required: true
  image-tag:
    description: Image tag
    required: true
  image-tags:
    description: Image tags
    required: true
  registry-server:
    default: docker.io
    description: Docker registry server
    required: true

runs:
  using: composite
  steps:
    - env:
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
        TAGS: ${{ steps.docker_meta_dockerhub.outputs.tags }}
      name: Sign the DockerHub images with GitHub OIDC Token
      run: |
        images=""
        for tag in ${TAGS}; do
          images+="${tag}@${DIGEST} "
        done
        cosign sign --yes ${images}

        echo "[INFO] cosign verify --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
          --certificate-identity=https://github.com/${{ github.workflow_ref }} \
          ${{ inputs.registry-server }}/${{ inputs.image-repository }}:${{ inputs.image-tag }}"
        cosign verify --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
          --certificate-identity=https://github.com/${{ github.workflow_ref }} \
          ${{ inputs.registry-server }}/${{ inputs.image-repository }}:${{ inputs.image-tag }}
      shell: bash
