name: Generate image attestations
description: Generate image attestations.
author: support@senzing.com

inputs:
  artifact-name-prefix:
    default: dockerhub
    description: Default branch of the repository
    required: true
  image-repository:
    description: Docker repository (e.g. senzing/senzingapi-runtime)
    required: true
  registry-server:
    default: docker.io
    description: Docker registry server
    required: true
  subject-digest:
    description: Image digest
    required: true

runs:
  using: composite
  steps:
    - uses: anchore/sbom-action@v0.18.0
      with:
        artifact-name: ${{ inputs.artifact-name-prefix }}-sbom.spdx
        format: spdx-json
        image: ${{ inputs.registry-server }}/${{ inputs.image-repository }}
        output-file: ${{ inputs.artifact-name-prefix }}-sbom.json

    - name: Generate artifact provenance attestation
      uses: actions/attest-build-provenance@v2
      with:
        push-to-registry: true
        subject-name: ${{ inputs.registry-server }}/${{ inputs.image-repository }}
        subject-digest: ${{ inputs.subject-digest }}

    - name: Generate SBOM attestation
      uses: actions/attest-sbom@v1
      with:
        subject-name: ${{ inputs.registry-server }}/${{ inputs.image-repository }}
        subject-digest: ${{ inputs.subject-digest }}
        sbom-path: ${{ inputs.artifact-name-prefix }}-sbom.json
        push-to-registry: true

    - env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        REGISTRY_SERVER: ${{ inputs.registry-server }}
        IMAGE_REPOSITORY: ${{ inputs.image-repository }}
        SUBJECT_DIGEST: ${{ inputs.subject-digest }}
      name: Verify DockerHub Attestation
      run: |
        gh attestation verify --repo "$GITHUB_REPOSITORY" "oci://${REGISTRY_SERVER}/${IMAGE_REPOSITORY}@${SUBJECT_DIGEST}"
        gh attestation verify --signer-repo "$GITHUB_REPOSITORY" --repo "$GITHUB_REPOSITORY" "oci://${REGISTRY_SERVER}/${IMAGE_REPOSITORY}@${SUBJECT_DIGEST}"
      shell: bash
